### ISSUE TITLE
Archive this repo in favor of the Google doc

### ISSUE THREAD

**Issue by kdmccormick** [openedx/tcril-onboarding#35]
transferring this over from https://github.com/openedx/axim-engineering/issues/795

_____________________

We have both:

* https://tcril-onboarding.readthedocs.io/en/latest/, built from https://github.com/aximcollaborative/axim-onboarding
* https://docs.google.com/document/d/1ya8WgQOlL5Nr6vT9-Ad5kr9WS7X4TEN-R46fnMUAxQU/edit

### Tasks
- [x] Choose one. WINNER: Google Doc.
- [x] Update the Google Doc with any missing info from ReadTheDocs.
- [x] Actually go through the onboarding process, and update the Google Doc with anything else that was missing.
- [x] Delete the tcril-onboarding ReadTheDocs project.
- [x] Archive the axim-onboarding source repo.
- [x] Does there need to be any additional "offboarding" info in the doc? If so, add it.

**Comment by sarina** [comment]
assigning @saraburns1 onboarding task to resolve this issue :)

**Comment by saraburns1** [comment]
Onboarding document updated! https://docs.google.com/document/d/1ya8WgQOlL5Nr6vT9-Ad5kr9WS7X4TEN-R46fnMUAxQU/edit#heading=h.6cspajd8zlhn

**Comment by saraburns1** [comment]
> ### Tasks
> * [x]  Choose one. WINNER: Google Doc.
> * [x]  Update the Google Doc with any missing info from ReadTheDocs.
> * [x]  Actually go through the onboarding process, and update the Google Doc with anything else that was missing.
> * [ ]  Delete the tcril-onboarding ReadTheDocs project.
> * [ ]  Archive the axim-onboarding source repo.
> * [x]  Does there need to be any additional "offboarding" info in the doc? If so, add it.
